// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkbyanfbinbtzulkibha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrYnlhbmZiaW5idHp1bGtpYmhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwMzE1NjMsImV4cCI6MjA5MDYwNzU2M30.dhQP24Mns9j6xBnvqjUOFSueE0aGsGQLsVnA6qRErO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});